// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonFooter: typeof import('./src/components/layout/commonFooter.vue')['default']
    CommonHeader: typeof import('./src/components/layout/commonHeader.vue')['default']
    ElAlert: typeof import('element-plus/lib')['ElAlert']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCarousel: typeof import('element-plus/lib')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/lib')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/lib')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/lib')['ElEmpty']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElImage: typeof import('element-plus/lib')['ElImage']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElPagination: typeof import('element-plus/lib')['ElPagination']
    ElSkeleton: typeof import('element-plus/lib')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/lib')['ElSkeletonItem']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    ElTabPane: typeof import('element-plus/lib')['ElTabPane']
    ElTabs: typeof import('element-plus/lib')['ElTabs']
    ElTag: typeof import('element-plus/lib')['ElTag']
    Pagination: typeof import('./src/components/common/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
